In [104]:
# Vectors
vec1 <- c("Apple", "Banana", "Cherry")
vec2 <- c(14, 12, 15.2)
vec3 <- 1:15
vec4 <- 1.5:6.4
'Vector 1'
vec1
'Vector 2'
vec2
'Vector 3'
vec3
'Vector 4'
vec4

[1] "Vector 1"

[1] "Apple"  "Banana" "Cherry"

[1] "Vector 2"

[1] 14.0 12.0 15.2

[1] "Vector 3"

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15

[1] "Vector 4"

[1] 1.5 2.5 3.5 4.5 5.5

In [3]:
# Vector of logical values
log_values <- c(TRUE, FALSE, TRUE, FALSE)
log_values

[1]  TRUE FALSE  TRUE FALSE

In [4]:
# Properties of  Vectors
# LENGTH
length(vec1)

[1] 3

In [5]:
# SORT
sort(vec2)
sort(vec1)

[1] 12.0 14.0 15.2

[1] "Apple"  "Banana" "Cherry"

In [16]:
# Access
vec1[1]
vec4[5]
'Multiple Access'
vec3[c(1:5)]
'Specified Access'
vec2[c(2)]
vec3[c(-1)]         # Gives all the values except the 1st value, say -5, then the 5th val will be missing
vec3[c(-5)]  

[1] "Apple"

[1] 5.5

[1] "Multiple Access"

[1] 1 2 3 4 5

[1] "Specified Access"

[1] 12

[1]  2  3  4  5  6  7  8  9 10 11 12 13 14 15

[1]  1  2  3  4  6  7  8  9 10 11 12 13 14 15

In [17]:
# Change an item
fruits <- c("Oranges", "Pears", "Kiwi", "Watermelon")
fruits[1] <- "Apple"
fruits

[1] "Apple"      "Pears"      "Kiwi"       "Watermelon"

In [22]:
# Repeat
repeat_each <- rep(fruits, each = 3)
repeat_each
'Individual count'
repeat1 <- rep(fruits, times = c(2,4,3,5))
repeat1
repeat2 <- rep(c(22, 34, 45), times = c(2,4,3))
repeat2

[1] "Apple"      "Apple"      "Apple"      "Pears"      "Pears"     
 [6] "Pears"      "Kiwi"       "Kiwi"       "Kiwi"       "Watermelon"
[11] "Watermelon" "Watermelon"

[1] "Individual count"

[1] "Apple"      "Apple"      "Pears"      "Pears"      "Pears"     
 [6] "Pears"      "Kiwi"       "Kiwi"       "Kiwi"       "Watermelon"
[11] "Watermelon" "Watermelon" "Watermelon" "Watermelon"

[1] 22 22 34 34 34 34 45 45 45

In [23]:
# Another way for sequenced vectors
'1. var <- 1:5'
'2. using seq(from= , to= , by=)'
num <- seq(from = 2, to = 14, by = 2)
num

[1] "1. var <- 1:5"

[1] "2. using seq(from= , to= , by=)"

[1]  2  4  6  8 10 12 14

In [24]:
# LISTS
lst <- list(22, 34, 56, 88)
lst

[[1]]
[1] 22

[[2]]
[1] 34

[[3]]
[1] 56

[[4]]
[1] 88

In [29]:
# Access
lst[3]
# Change
lst[1] <- 44
lst
#Length
paste('length =', length(lst))

[[1]]
[1] 56

[[1]]
[1] 44

[[2]]
[1] 34

[[3]]
[1] 56

[[4]]
[1] 88

[1] "length = 4"

In [30]:
# Check if it exists
"Apple" %in% fruits

[1] TRUE

In [33]:
# Add elements
append(lst, 1001)
append(fruits, "Banana", after = 2)

[[1]]
[1] 44

[[2]]
[1] 34

[[3]]
[1] 56

[[4]]
[1] 88

[[5]]
[1] 1001

[1] "Apple"      "Pears"      "Banana"     "Kiwi"       "Watermelon"

In [36]:
# Remove elements
# using negative indexing which displayes other elements except that position
fruits
fruits -> edit_fruits
edit_fruits[-2]

[1] "Apple"      "Pears"      "Kiwi"       "Watermelon"

[1] "Apple"      "Kiwi"       "Watermelon"

In [37]:
# Range
(lst)[1:3]

[[1]]
[1] 44

[[2]]
[1] 34

[[3]]
[1] 56

In [38]:
# Loop
thislist <- list("apple", "banana", "cherry")

for (x in thislist) {
  print(x)
}

[1] "apple"
[1] "banana"
[1] "cherry"


In [40]:
# Join 2 lists
lst2 <- c(lst, fruits)
lst2

[[1]]
[1] 44

[[2]]
[1] 34

[[3]]
[1] 56

[[4]]
[1] 88

[[5]]
[1] "Apple"

[[6]]
[1] "Pears"

[[7]]
[1] "Kiwi"

[[8]]
[1] "Watermelon"

In [43]:
# Matrices
m1 <- matrix(c(2,4,5,1,4,2), nrow = 2, ncol = 3)
m2 <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
m1
m2

[,1] [,2] [,3]
[1,] 2    5    4   
[2,] 4    1    2

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

In [47]:
# Access Matrix Items
m1[1,3]        # row, col
m2[2,2]
m1[1,]
m2[,1]

[1] 4

[1] "orange"

[1] 2 5 4

[1] "apple"  "banana"

In [49]:
# Access more than 1 row
thismatrix <- matrix(c("apple", "banana", "cherry", "orange","grape", "pineapple", "pear", "melon", "fig"), nrow = 3, ncol = 3)
thismatrix[c(1,2),]
thismatrix[, c(1,2)]

[,1]   [,2]   [,3] 
[1,] apple  orange pear 
[2,] banana grape  melon

[,1]   [,2]     
[1,] apple  orange   
[2,] banana grape    
[3,] cherry pineapple

In [54]:
# Add rows and cols
"Adding Cols"
m1
new_m1 <- cbind(m1, c(2,7))
new_m1
'Adding Rows'
m2
new_m2 <- rbind(m2, c("Pear", "Kiwi"))
new_m2

[1] "Adding Cols"

[,1] [,2] [,3]
[1,] 2    5    4   
[2,] 4    1    2

[,1] [,2] [,3] [,4]
[1,] 2    5    4    2   
[2,] 4    1    2    7

[1] "Adding Rows"

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange
[3,] Pear   Kiwi

In [60]:
# Remove rows and cols
matrix1 <- matrix(c(11, 12, 13, 14, 15, 16, 17, 18, 19), ncol = 3, nrow = 3)
matrix2 <- matrix1[-c(1), -c(1)]
matrix3 <- matrix1[-c(2), -c(1)]
matrix1
matrix2
matrix3

[,1] [,2] [,3]
[1,] 11   14   17  
[2,] 12   15   18  
[3,] 13   16   19

[,1] [,2]
[1,] 15   18  
[2,] 16   19

[,1] [,2]
[1,] 14   17  
[2,] 16   19

In [61]:
# Check if its there
m2 <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
"apple" %in% m2

[1] TRUE

In [64]:
# Dimensions / number of elements
dim(m2)
# Length
length(m2)      # multiples the dimensions

[1] 2 2

[1] 4

In [66]:
# Loops
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


In [69]:
# Combine Two matrices
mx1 <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)
mx2 <- matrix(c("pear", "kiwi", "blueberry", "jackfruit"), nrow = 2, ncol = 2)
"Original matrices"
mx1
mx2
""
c_combined <- cbind(mx1, mx2)
r_combined <- rbind(mx1, mx2)
'Combined matrices'
c_combined
r_combined

[1] "Original matrices"

[,1]   [,2]  
[1,] apple  cherry
[2,] banana orange

[,1] [,2]     
[1,] pear blueberry
[2,] kiwi jackfruit

[1] ""

[1] "Combined matrices"

[,1]   [,2]   [,3] [,4]     
[1,] apple  cherry pear blueberry
[2,] banana orange kiwi jackfruit

[,1]   [,2]     
[1,] apple  cherry   
[2,] banana orange   
[3,] pear   blueberry
[4,] kiwi   jackfruit

In [76]:
# Arrays
thisarray <- c(1:24)
arr2 <- array(thisarray, dim = c(4, 3, 2))
# The first and second number in the bracket specifies the amount of rows and columns.
# The last number in the bracket specifies how many dimensions we want.
arr2

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24

In [81]:
# Access
arr2[2, 3, 2]     # The syntax is as follow: array[row position, column position, matrix level]
arr2[c(1),,1]
arr2[,c(1),1]

[1] 22

[1] 1 5 9

[1] 1 2 3 4

In [82]:
# Check if it exists
2 %in% arr2

[1] TRUE

In [85]:
# Dimension / length
dim(arr2)
length(arr2)

[1] 4 3 2

[1] 24

In [86]:
# Loop
for(x in arr2){
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24


In [88]:
# DATAFRAMES
Data_Frame <- data.frame (
  Subject = c("Economics", "DS", "Maths"),
  Credits = c(4, 5, 7),
  Duration = c(30, 60, 75)
)
Data_Frame

Subject   Credits Duration
1 Economics 4       30      
2 DS        5       60      
3 Maths     7       75

In [89]:
#Summarize the table
summary(Data_Frame)

      Subject     Credits         Duration   
 DS       :1   Min.   :4.000   Min.   :30.0  
 Economics:1   1st Qu.:4.500   1st Qu.:45.0  
 Maths    :1   Median :5.000   Median :60.0  
               Mean   :5.333   Mean   :55.0  
               3rd Qu.:6.000   3rd Qu.:67.5  
               Max.   :7.000   Max.   :75.0  

In [91]:
# Access items
# We can use single brackets [ ], double brackets [[ ]] or $ to access columns from a data frame
Data_Frame[1]
Data_Frame[["Subject"]]
Data_Frame$Subject

Subject  
1 Economics
2 DS       
3 Maths

[1] Economics DS        Maths    
Levels: DS Economics Maths

[1] Economics DS        Maths    
Levels: DS Economics Maths

In [96]:
# Add a new row
New_row_DF <- rbind(Data_Frame, c("Economics", 7, 90))
# Add a new column
New_col_DF <- cbind(Data_Frame, Fees = c(1000, 6000, 2000))
New_row_DF
New_col_DF
# Remove the first row and column
Data_Frame_New <- Data_Frame[-c(1), -c(1)]
Data_Frame_New

Subject   Credits Duration
1 Economics 4       30      
2 DS        5       60      
3 Maths     7       75      
4 Economics 7       90

Subject   Credits Duration Fees
1 Economics 4       30       1000
2 DS        5       60       6000
3 Maths     7       75       2000

Credits Duration
2 5       60      
3 7       75

In [100]:
# Dimentions / length
dim(Data_Frame)
'No. of cols'
ncol(Data_Frame)
'No. of rows'
nrow(Data_Frame)
'Length'
length(Data_Frame)

[1] 3 3

[1] "No. of cols"

[1] 3

[1] "No. of rows"

[1] 3

[1] "Length"

[1] 3

In [103]:
# Combining 2 DFs
df1 <- data.frame(
    "Name" = c("Abhay", "Akshay", "Ashwin"),
    "Year" = c(2005, 2004, 2006),
    "Course" = c("Bio-Math", "CS", "Commerce"),
    "CGPA" = c(8.9, 8.8, 9)
)
df2 <- data.frame(
    "Name" = c("Aadya", "Abhinaya", "Arun"),
    "Year" = c(2005, 2004, 2006),
    "Course" = c("CS-Math", "PCM", "Commerce"),
    "CGPA" = c(9.9, 7.8, 6)
)

c_com <- cbind(df1, df2)
r_com <- rbind(df1, df2)
c_com
r_com

Name   Year Course   CGPA Name     Year Course   CGPA
1 Abhay  2005 Bio-Math 8.9  Aadya    2005 CS-Math  9.9 
2 Akshay 2004 CS       8.8  Abhinaya 2004 PCM      7.8 
3 Ashwin 2006 Commerce 9.0  Arun     2006 Commerce 6.0

Name     Year Course   CGPA
1 Abhay    2005 Bio-Math 8.9 
2 Akshay   2004 CS       8.8 
3 Ashwin   2006 Commerce 9.0 
4 Aadya    2005 CS-Math  9.9 
5 Abhinaya 2004 PCM      7.8 
6 Arun     2006 Commerce 6.0

In [105]:
# FACTOR
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))
music_genre
levels(music_genre)

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

[1] "Classic" "Jazz"    "Pop"     "Rock"

In [106]:
# Can also set the levels, by adding the levels argument inside the factor() function
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))
levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

In [108]:
# Length
length(music_genre)
# Access
music_genre[3]

[1] 8

[1] Classic
Levels: Classic Jazz Pop Rock Other

In [109]:
# Change
music_genre[2] <- "Pop"
music_genre[2]

[1] Pop
Levels: Classic Jazz Pop Rock Other